trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'NomeDaSuaConexaoAzure'  # Substitua pelo nome da sua conexão de serviço Azure
  appName: 'nome-do-seu-app'                  # Substitua pelo nome do seu Azure App Service
  packagePath: 'target/*.jar'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests'
  displayName: 'Build with Maven'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'  # Ajuste para 'webApp' se for Windows
    appName: '$(appName)'
    package: '$(System.DefaultWorkingDirectory)/target/*.jar'
  displayName: 'Deploy to Azure Web App'
