trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'ponabri-abfmh6c4gwdmbngy.brazilsouth-01.azurewebsites.net'  
  appName: 'ponabri'                
  packagePath: 'target/*.jar'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests'
  displayName: 'Build with Maven'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp' 
    appName: '$(appName)'
    package: '$(System.DefaultWorkingDirectory)/target/*.jar'
  displayName: 'Deploy to Azure Web App'